### ISSUE TITLE
WorldEdit Module - UnsupportedOperationException: null

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena_modules#4] opened 2020-05-22 03:28 UTC
PVPArena dev 316
Modules dev 204
WorldEdit dev 5013

Caused by breaking commit https://github.com/Eredrim/pvparena_modules/commit/8c6a61dc948db716f6fe2c6577feaf6f00b80ca2
```
[13:40:58] [Server thread/WARN]: [PVP Arena] Task #892010 for pvparena v1.14.1-SNAPSHOT-b316 generated an exception
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at com.sk89q.worldedit.extent.world.SideEffectExtent$1.resume(SideEffectExtent.java:113) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:829) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:289) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:254) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.reset(PAWE.java:344) ~[?:?]
	at net.slipcor.pvparena.loadables.ArenaModuleManager.reset(ArenaModuleManager.java:266) ~[?:?]
	at net.slipcor.pvparena.arena.Arena.reset(Arena.java:1454) ~[?:?]
	at net.slipcor.pvparena.runnables.EndRunnable.commit(EndRunnable.java:53) ~[?:?]
	at net.slipcor.pvparena.runnables.ArenaRunnable.run(ArenaRunnable.java:161) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1316) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1231) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Tuinity-"d83d065"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Eredrim** [comment] 2020-05-28 13:16
Hello,
Worldedit implementation of PvPArena respects strictly worldedit documentation. I can reproduce the issue but I think problem comes from Worldedit. Their dev build still unstable (logical because they're dev builds) and I think the problem will disappear by itself when final 7.2.0 version will be released.
So I close this ticket.

_NB : I will close the issue board of the "pvparena_modules" project to centralize every issues in the github project of pvparena_

**Comment by mibby** [comment] 2020-05-28 21:24
@Eredrim Are you sure it is an issue with WorldEdit itself and not the module? Using the WorldEdit module prior to your commit change works fine with dev builds of WorldEdit. The only noteworthy change I could really find to EditSession.java in WorldEdit as of the last couple months is a change to FastMode - which your commit doesn't touch that.

https://github.com/EngineHub/WorldEdit/commit/865c3a24d25156cbffbf44630506a08d2ff4755a#diff-95e51862b670688298a968792897339f

However older PA WorldEdit module versions still work perfectly fine without issues.

I stick with the dev builds for WorldEdit because it's been for the most part stable without any compatibility issues or problems, is usually recommended when updating, and takes months/years for new "final version" public builds to come out if you require a fix or optimization. 

![link](https://i.imgur.com/GZmrJhW.png)

**Comment by Eredrim** [comment] 2020-05-28 22:31
Yes I'm pretty sure problem comes from WorldEdit, and precisely when FAST reorder mode is used with fast mode. All works perfectly with versions 7.0 and above, except for current snapshots. So I think you can open an issue (if you want), however I'll do it.

The objective of using the FAST reorder mode is to improve loading efficiency. By the way, WorldEdit documentation itself suggest to use it for mods.

For fun, I tried to used default reorder mode (MULTI_STAGE), it works bu all saplings of the loaded area are destroyed. So it's not better 😄 

I understand your reasons to use WorldEdit dev builds, but you also have to understand I can't guarantee compatibility with versions which are likely to be changed. I try to stay as cross-compatible as possible, but some things still just not possible. Waiting WorldEdit answers, you can continue using the old version of PA_WorldEdit, modules versions can be mixed without any problem.

**Comment by mibby** [comment] 2020-06-02 12:04
Testing as of module dev 205 / commit https://github.com/Eredrim/pvparena_modules/commit/70474da57672891048d6a28bd88ac2a987dc0279 with WorldEdit dev 5017;

```
[05:00:15] [Server thread/INFO]: mibby issued server command: /pa Spleef regload floor
[05:00:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pa' in plugin pvparena v1.15.0-SNAPSHOT-b327
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1872) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1680) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at xuan.cat.XuanCatAPI.a.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.a.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.a.b.c.a.g.a(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1159) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1152) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1128) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	at com.sk89q.worldedit.extent.world.SideEffectExtent$1.resume(SideEffectExtent.java:113) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:831) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:293) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.load(PAWE.java:254) ~[?:?]
	at net.slipcor.pvparena.modules.worldedit.PAWE.commitCommand(PAWE.java:115) ~[?:?]
	at net.slipcor.pvparena.classes.PACheck.handleCommand(PACheck.java:146) ~[?:?]
	at net.slipcor.pvparena.PVPArena.onCommand(PVPArena.java:371) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Tuinity-"aadb94d"]
	... 20 more
```

The floor did seem to paste, just errored after typing the command. I assume the previous error would occur as well on game end.

> So I think you can open an issue (if you want), however I'll do it.
> Waiting WorldEdit answers, you can continue using the old version of PA_WorldEdit, modules versions can be mixed without any problem.

I'll just use the old module version for now until you hear back from WorldEdit.

**Comment by Eredrim** [comment] 2020-06-02 19:14
WorldEdit issue was opened : 
https://github.com/EngineHub/WorldEdit/issues/1354

**Comment by Eredrim** [comment] 2020-06-02 23:06
Fixed by WorldEdit Team. You can use [7.2.0-SNAPSHOT #5018 or below](https://builds.enginehub.org/job/worldedit)

**Closed by Eredrim** 2020-06-02 23:06 UTC
